// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Kaya Yesilyurt - Atlas Chronicles. Siehe LICENSE.
import { useRef, useState } from "react";
import { Check, Copy, KeyRound, Link, RefreshCw, UserPlus, Users } from "lucide-react";
import { Button, EmptyState, Loading, Notice } from "@chronicle/ui";
import { api, apiPath, type Campaign, type Invitation, type JoinRequest, type Member } from "./api";
import { useResource, useTask } from "./hooks";
import { CampaignExport } from "./features/CampaignExport";
import { locale, plural, t } from "./i18n";

export function Round({ campaign }: { campaign: Campaign }) {
  const [revision, setRevision] = useState(0), [invitation, setInvitation] = useState<Invitation | null>(null), [notice, setNotice] = useState(""), [pairCode, setPairCode] = useState(""), [linkCopied, setLinkCopied] = useState(false);
  const task = useTask(), roster = useResource<Member[]>(apiPath(campaign.id, "/roster"), revision, 5000);
  const pending = useResource<JoinRequest[]>(campaign.role === "leitung" ? apiPath(campaign.id, "/joins") : null, revision, 3000);
  const invitations = useResource<{ id: string; createdAt: string | number; expiresAt: string | number; revokedAt: string | number | null }[]>(campaign.role === "leitung" ? apiPath(campaign.id, "/invitations") : null, revision);
  const inviteUrl = invitation ? `${location.origin}/?join=${encodeURIComponent(invitation.code)}` : "";
  const inviteField = useRef<HTMLInputElement>(null);
  const copyInvitation = async () => {
    let copied = false;
    try { if (navigator.clipboard) { await navigator.clipboard.writeText(inviteUrl); copied = true; } } catch { /* Use the selected field when clipboard permission is unavailable. */ }
    if (!copied) {
      inviteField.current?.focus(); inviteField.current?.select();
      try { copied = document.execCommand("copy"); } catch { /* The selected link remains available for manual copying. */ }
    }
    setLinkCopied(copied);
    setNotice(copied ? t("Einladungslink kopiert.") : t("Der Link ist markiert. Kopiere ihn mit Strg+C oder über das Kontextmenü."));
  };
  const pendingCount = pending.data?.length ?? 0;
  return <section className="page-content"><div className="page-heading"><div><p className="eyebrow">{t("Gemeinsam Geschichten schreiben")}</p><h1>{t("Deine Runde")}</h1><p className="muted">{campaign.name}</p></div><Button aria-label={t("Runde aktualisieren")} onClick={() => setRevision((v) => v + 1)}><RefreshCw size={17} /></Button></div>
    {task.error ? <Notice error>{task.error}</Notice> : null}{notice ? <Notice>{notice}</Notice> : null}{campaign.role === "leitung" && pendingCount > 0 ? <Notice>{plural(pendingCount, "Eine Person wartet vor der Tür auf deine Freigabe.", "{n} Personen warten vor der Tür auf deine Freigabe.")}</Notice> : null}
    <div className="round-grid"><section className="panel"><div className="section-heading"><h2><Users size={20} /> {t("Am Tisch")}</h2></div>
      {roster.loading ? <Loading /> : roster.error ? <Notice error>{roster.error}</Notice> : roster.data?.length ? <ul className="member-list">{roster.data.map((member) => <li key={member.userId}><span className="avatar">{member.displayName.slice(0, 1).toUpperCase()}</span><div><strong>{member.displayName}</strong><small>{member.role === "leitung" ? t("Spielleitung") : member.role === "spieler" ? t("Spieler · eigene Figur") : t("Beobachter")}</small></div>{campaign.role === "leitung" ? <Button aria-label={t("Gerät für {name} koppeln", { name: member.displayName })} title={t("Neues Gerät für {name} koppeln", { name: member.displayName })} onClick={() => void task.run(async () => {
        const result = await api<{ code: string }>(apiPath(campaign.id, "/pairing"), { method: "POST", body: { userId: member.userId } }); setPairCode(result.code);
      })} disabled={task.busy}><KeyRound size={16} /></Button> : null}</li>)}</ul> : <p className="muted">{campaign.role === "leitung" ? t("Noch ist niemand da außer dir. Erzeuge eine Einladung und schick den Link los, um jemanden hinzuzufügen.") : t("Noch ist niemand in der Runde. Bitte die Spielleitung um einen Einladungslink.")}</p>}
      {pairCode ? <div className="code-card"><label>{t("Einmaliger Kopplungscode")}<input readOnly value={pairCode} onFocus={(e) => e.target.select()} /></label><p className="field-help">{t("Gib diesen Code nur an die zugehörige Person für ihr neues Gerät weiter. Er bleibt gültig, bis er benutzt wird oder abläuft – auch wenn du ihn hier ausblendest.")}</p><Button onClick={() => setPairCode("")}>{t("Code ausblenden")}</Button></div> : null}
    </section>
    {campaign.role === "leitung" ? <section className="panel"><div className="section-heading"><h2><UserPlus size={20} /> {t("Die Tür öffnen")}</h2></div><p className="muted">{t("So kommt jemand Neues dazu: Link erzeugen, weitergeben, Beitritt bei „Vor der Tür“ freigeben. Die eingeladene Person öffnet den Link, nennt ihren Namen und wartet danach auf deine Freigabe – vorher ist sie noch nicht in der Runde.")}</p>
      <Button variant="primary" disabled={task.busy} onClick={() => void task.run(async () => { setInvitation(await api<Invitation>(apiPath(campaign.id, "/invitations"), { method: "POST", body: {} })); setLinkCopied(false); setNotice(""); setRevision((v) => v + 1); })}><Link size={16} /> {t("Einladung erstellen")}</Button>
      {invitation ? <div className="code-card"><label>{t("Einladungslink")}<input ref={inviteField} value={inviteUrl} readOnly onFocus={(e) => e.target.select()} /></label><p className="field-help">{t("Gültig bis {zeitpunkt}. Nächster Schritt: Link kopieren und der eingeladenen Person schicken.", { zeitpunkt: new Date(invitation.expiresAt).toLocaleString(locale()) })}</p><div className="button-row"><Button onClick={() => void task.run(copyInvitation)}>{linkCopied ? <><Check size={14} /> {t("Kopiert")}</> : <><Copy size={14} /> {t("Kopieren")}</>}</Button><Button variant="danger" onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/invitations/${encodeURIComponent(invitation.id)}`), { method: "DELETE" }); setInvitation(null); setNotice(t("Einladung widerrufen – der Link funktioniert ab sofort nicht mehr.")); setRevision((v) => v + 1); })}>{t("Link widerrufen")}</Button></div><p className="field-help">{t("Widerrufen macht nur den Link ungültig – auch offene Beitrittsanfragen darüber verfallen dann. Bereits beigetretene Mitglieder bleiben in der Runde.")}</p></div> : null}
      {invitations.error ? <Notice error>{invitations.error}</Notice> : invitations.data?.length ? <details><summary>{t("Ausgestellte Einladungen verwalten")}</summary><p className="field-help">{t("Widerrufen setzt den jeweiligen Link sofort außer Kraft – auch noch offene Beitrittsanfragen darüber verfallen dann.")}</p><ul className="credential-list">{invitations.data.map((item) => <li key={item.id}><div><strong>{t("Einladung vom {datum}", { datum: new Date(Number(item.createdAt)).toLocaleDateString(locale()) })}</strong><small>{item.revokedAt ? t("Widerrufen") : Number(item.expiresAt) <= Date.now() ? t("Abgelaufen") : t("Gültig bis {zeitpunkt}", { zeitpunkt: new Date(Number(item.expiresAt)).toLocaleString(locale()) })}</small></div>{!item.revokedAt && Number(item.expiresAt) > Date.now() ? <Button variant="danger" disabled={task.busy} onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/invitations/${encodeURIComponent(item.id)}`), { method: "DELETE" }); if (invitation?.id === item.id) { setInvitation(null); setLinkCopied(false); } setRevision((v) => v + 1); setNotice(t("Einladung widerrufen.")); })}>{t("Widerrufen")}</Button> : null}</li>)}</ul></details> : null}
    </section> : null}</div>
    {campaign.role === "leitung" ? <section className="panel requests-panel"><div className="section-heading"><h2>{t("Vor der Tür")}{pendingCount > 0 ? <span className="role-chip" aria-label={t("{n} wartend", { n: pendingCount })}>{pendingCount}</span> : null}</h2><span className="muted">{t("Beitrittsanfragen")}</span></div>{pending.error ? <Notice error>{pending.error}</Notice> : pending.loading ? <Loading /> : pending.data?.length ? <ul className="member-list">{pending.data.map((request) => <li key={request.id}><span className="avatar pending">{request.displayName.slice(0, 1).toUpperCase()}</span><div><strong>{request.displayName}</strong><small>{t("Wartet auf deine Freigabe")}</small></div><Button disabled={task.busy} variant="primary" onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/joins/${encodeURIComponent(request.id)}/approve`), { method: "POST" }); setRevision((v) => v + 1); setNotice(t("{name} darf der Runde beitreten und erscheint jetzt am Tisch.", { name: request.displayName })); })}><Check size={16} /> {t("Freigeben")}</Button><Button disabled={task.busy} onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/joins/${encodeURIComponent(request.id)}/reject`), { method: "POST" }); setRevision((v) => v + 1); setNotice(t("Die Anfrage von {name} ist abgelehnt.", { name: request.displayName })); })}>{t("Ablehnen")}</Button></li>)}</ul> : <EmptyState title={t("Die Tür ist ruhig.")}>{t("Neue Beitrittsanfragen erscheinen hier automatisch, sobald jemand deinen Einladungslink nutzt.")}</EmptyState>}</section> : null}
    {campaign.role === "leitung" ? <CampaignExport campaignId={campaign.id} /> : null}
  </section>;
}
