import { useState } from "react";
import { Check, Copy, KeyRound, Link, RefreshCw, UserPlus, Users } from "lucide-react";
import { Button, EmptyState, Loading, Notice } from "@chronicle/ui";
import { api, apiPath, type Campaign, type Invitation, type JoinRequest, type Member } from "./api";
import { useResource, useTask } from "./hooks";
import { CampaignExport } from "./features/CampaignExport";

export function Round({ campaign }: { campaign: Campaign }) {
  const [revision, setRevision] = useState(0), [invitation, setInvitation] = useState<Invitation | null>(null), [notice, setNotice] = useState(""), [pairCode, setPairCode] = useState("");
  const task = useTask(), roster = useResource<Member[]>(apiPath(campaign.id, "/roster"), revision, 5000);
  const pending = useResource<JoinRequest[]>(campaign.role === "leitung" ? apiPath(campaign.id, "/joins") : null, revision, 3000);
  const invitations = useResource<{ id: string; createdAt: string | number; expiresAt: string | number; revokedAt: string | number | null }[]>(campaign.role === "leitung" ? apiPath(campaign.id, "/invitations") : null, revision);
  const inviteUrl = invitation ? `${location.origin}/?join=${encodeURIComponent(invitation.code)}` : "";
  return <section className="page-content"><div className="page-heading"><div><p className="eyebrow">Gemeinsam Geschichten schreiben</p><h1>Deine Runde</h1><p className="muted">{campaign.name}</p></div><Button aria-label="Runde aktualisieren" onClick={() => setRevision((v) => v + 1)}><RefreshCw size={17} /></Button></div>
    {task.error ? <Notice error>{task.error}</Notice> : null}{notice ? <Notice>{notice}</Notice> : null}
    <div className="round-grid"><section className="panel"><div className="section-heading"><h2><Users size={20} /> Am Tisch</h2></div>
      {roster.loading ? <Loading /> : roster.error ? <Notice error>{roster.error}</Notice> : <ul className="member-list">{roster.data?.map((member) => <li key={member.userId}><span className="avatar">{member.displayName.slice(0, 1).toUpperCase()}</span><div><strong>{member.displayName}</strong><small>{member.role === "leitung" ? "Spielleitung" : member.role === "spieler" ? "Spieler · eigene Figur" : "Beobachter"}</small></div>{campaign.role === "leitung" ? <Button aria-label={`Gerät für ${member.displayName} koppeln`} onClick={() => void task.run(async () => {
        const result = await api<{ code: string }>(apiPath(campaign.id, "/pairing"), { method: "POST", body: { userId: member.userId } }); setPairCode(result.code);
      })} disabled={task.busy}><KeyRound size={16} /></Button> : null}</li>)}</ul>}
      {pairCode ? <div className="code-card"><label>Einmaliger Kopplungscode<input readOnly value={pairCode} onFocus={(e) => e.target.select()} /></label><p className="field-help">Gib diesen Code nur an die zugehörige Person für ihr neues Gerät weiter.</p><Button onClick={() => setPairCode("")}>Code ausblenden</Button></div> : null}
    </section>
    {campaign.role === "leitung" ? <section className="panel"><div className="section-heading"><h2><UserPlus size={20} /> Die Tür öffnen</h2></div><p className="muted">Teile einen Einladungslink. Wer beitritt, kommt erst nach deiner Freigabe in die Runde.</p>
      <Button variant="primary" disabled={task.busy} onClick={() => void task.run(async () => { setInvitation(await api<Invitation>(apiPath(campaign.id, "/invitations"), { method: "POST", body: {} })); setNotice(""); setRevision((v) => v + 1); })}><Link size={16} /> Einladung erstellen</Button>
      {invitation ? <div className="code-card"><label>Einladungslink<input value={inviteUrl} readOnly onFocus={(e) => e.target.select()} /></label><p className="field-help">Gültig bis {new Date(invitation.expiresAt).toLocaleString("de-DE")}</p><div className="button-row"><Button onClick={() => void task.run(async () => { await navigator.clipboard.writeText(inviteUrl); setNotice("Einladungslink kopiert."); })}><Copy size={14} /> Kopieren</Button><Button variant="danger" onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/invitations/${encodeURIComponent(invitation.id)}`), { method: "DELETE" }); setInvitation(null); setNotice("Einladung widerrufen."); setRevision((v) => v + 1); })}>Widerrufen</Button></div></div> : null}
      {invitations.error ? <Notice error>{invitations.error}</Notice> : invitations.data?.length ? <details><summary>Ausgestellte Einladungen verwalten</summary><ul className="credential-list">{invitations.data.map((item) => <li key={item.id}><div><strong>Einladung vom {new Date(Number(item.createdAt)).toLocaleDateString("de-DE")}</strong><small>{item.revokedAt ? "Widerrufen" : Number(item.expiresAt) <= Date.now() ? "Abgelaufen" : `Gültig bis ${new Date(Number(item.expiresAt)).toLocaleString("de-DE")}`}</small></div>{!item.revokedAt && Number(item.expiresAt) > Date.now() ? <Button variant="danger" disabled={task.busy} onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/invitations/${encodeURIComponent(item.id)}`), { method: "DELETE" }); if (invitation?.id === item.id) setInvitation(null); setRevision((v) => v + 1); setNotice("Einladung widerrufen."); })}>Widerrufen</Button> : null}</li>)}</ul></details> : null}
    </section> : null}</div>
    {campaign.role === "leitung" ? <section className="panel requests-panel"><div className="section-heading"><h2>Vor der Tür</h2><span className="muted">Beitrittsanfragen</span></div>{pending.error ? <Notice error>{pending.error}</Notice> : pending.loading ? <Loading /> : pending.data?.length ? <ul className="member-list">{pending.data.map((request) => <li key={request.id}><span className="avatar pending">{request.displayName.slice(0, 1).toUpperCase()}</span><div><strong>{request.displayName}</strong><small>Wartet auf deine Freigabe</small></div><Button disabled={task.busy} variant="primary" onClick={() => void task.run(async () => { await api(apiPath(campaign.id, `/joins/${encodeURIComponent(request.id)}/approve`), { method: "POST" }); setRevision((v) => v + 1); setNotice(`${request.displayName} darf der Runde beitreten.`); })}><Check size={16} /> Freigeben</Button></li>)}</ul> : <EmptyState title="Die Tür ist ruhig.">Neue Beitrittsanfragen erscheinen hier automatisch.</EmptyState>}</section> : null}
    {campaign.role === "leitung" ? <CampaignExport campaignId={campaign.id} /> : null}
  </section>;
}
