import { test, expect, type BrowserContext } from "@playwright/test";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import { readFile } from "node:fs/promises";
import { buildApp } from "../packages/server/src/app.ts";
import { createTestDb, migrate, type Db } from "../packages/server/src/db/index.ts";
import { createIdentity } from "../packages/server/src/identity/index.ts";
import { createCampaigns } from "../packages/server/src/domain/campaigns.ts";
import { fitCamera } from "../packages/render/src/geometry.ts";

// An isolated PostgreSQL-compatible database and real HTTP/UI; no application API mocks.
test("ERON markers open persistent nested maps, edit, restore navigation and work on mobile", async ({ browser }, testInfo) => {
  test.setTimeout(240_000);
  let db: Db | undefined, app: Awaited<ReturnType<typeof buildApp>> | undefined, context: BrowserContext | undefined;
  try {
    db = await createTestDb(); await migrate(db);
    const port = 9750 + Math.floor(Math.random() * 100), origin = `http://localhost:${port}`;
    const config = { origin, cookieSecret: randomBytes(32).toString("hex"), bootstrapToken: randomBytes(32).toString("hex"), staticRoot: resolve("packages/client/dist") };
    const gm = await createIdentity(db, config).bootstrap("Kartenleitung");
    const campaign = await createCampaigns(db).createCampaign(gm.userId, { name: "ERON · Die verschachtelte Welt" });
    app = await buildApp(db, config); await app.listen({ host: "127.0.0.1", port });
    context = await browser.newContext();
    await context.addCookies([{ name: "chronicle_session", value: gm.value, url: origin, httpOnly: true, sameSite: "Strict" }]);
    const page = await context.newPage(), errors: string[] = [], loadedAssets = new Set<string>(), failedAssets = new Set<string>();
    page.on("pageerror", error => errors.push(error.message));
    page.on("response", response => { if (/\/api\/packs\/[^/]+\/asset\//.test(response.url())) {
      if (response.ok()) loadedAssets.add(response.url()); else failedAssets.add(response.url());
    } });
    await page.goto(`${origin}/?campaign=${campaign.id}&stage=atlas`);
    const background = page.waitForResponse(response => /\/maps\/[^/]+\/image$/.test(response.url()) && response.ok());
    await page.getByRole("button", { name: "ERON-Karte öffnen", exact: true }).click();
    await expect(page.locator(".atlas-place-list li")).toHaveCount(191);
    await expect(page.locator(".atlas-render-host canvas")).toBeVisible();
    expect((await background).headers()["content-type"]).toContain("image/webp");
    await page.locator(".atlas-place-list").getByRole("button", { name: /^Akkator/ }).click();
    await page.getByRole("button", { name: "Unterkarte erzeugen", exact: true }).click();
    await expect(page.getByRole("region", { name: "Unterkarte", exact: true })).toBeVisible();
    await expect(page.locator('.tactical-canvas[data-canvas-ready="true"]')).toHaveCount(1);
    await expect.poll(() => loadedAssets.size).toBeGreaterThan(0);
    await expect(page.getByText(/Ein Teil der Kartenobjekte/)).toHaveCount(0);
    expect(failedAssets.size).toBe(0);
    const first = new URL(page.url()).searchParams.get("atlasChild")!;
    await expect(page.locator(".nested-map-rooms li").first()).toBeVisible();
    await page.locator(".nested-map-rooms li button").first().click();
    await page.getByRole("button", { name: "Unterkarte erzeugen", exact: true }).click();
    await expect.poll(() => { const id = new URL(page.url()).searchParams.get("atlasChild"); return !!id && id !== first; }).toBe(true);
    const second = new URL(page.url()).searchParams.get("atlasChild")!;
    expect(second).toBeTruthy();
    await expect(page.getByRole("navigation", { name: "Kartenpfad" }).locator("button[aria-current=page]")).toBeVisible();
    await page.getByRole("button", { name: "Karte bearbeiten", exact: true }).click();
    await page.getByRole("combobox", { name: "Kartenraster", exact: true }).selectOption("none");
    await page.getByRole("button", { name: "Kartenrevision speichern", exact: true }).click();
    await expect(page.getByText(/Kartenrevision 2\./)).toBeVisible();
    await page.getByRole("button", { name: "Karte ansehen", exact: true }).click();
    await page.reload();
    await expect(page.getByRole("region", { name: "Unterkarte", exact: true })).toBeVisible();
    expect(new URL(page.url()).searchParams.get("atlasChild")).toBe(second);
    await page.getByRole("button", { name: "Karte bearbeiten", exact: true }).click();
    await expect(page.getByRole("combobox", { name: "Kartenraster", exact: true })).toHaveValue("none");
    await page.getByRole("button", { name: "Karte ansehen", exact: true }).click();
    await page.screenshot({ path: testInfo.outputPath("nested-desktop.png"), fullPage: true });
    await page.getByRole("button", { name: "Hauptkarte", exact: true }).click();
    await expect(page.locator(".atlas-render-host canvas")).toBeVisible();
    const rootId = await page.locator("#atlas-map-select").inputValue();
    const root = await (await page.request.get(`${origin}/api/campaigns/${campaign.id}/maps/${rootId}`)).json();
    const pin = root.pins.find((item: { label: string }) => item.label === "Akkator");
    expect(pin.icon).toBe("portal");
    await page.getByRole("button", { name: "Gesamte Karte anzeigen" }).click();
    const bounds = (await page.locator(".atlas-render-host canvas").boundingBox())!;
    const camera = fitCamera([root.width, root.height], [bounds.width, bounds.height]);
    await page.mouse.click(bounds.x + camera.x + pin.x * camera.scale, bounds.y + camera.y + pin.y * camera.scale);
    await expect.poll(() => new URL(page.url()).searchParams.get("atlasChild")).toBe(first);
    const count = (await db.query<{ count: string }>("SELECT count(*)::text AS count FROM tactical_maps WHERE campaign_id=$1", [campaign.id])).rows[0]!.count;
    expect(count).toBe("2");
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole("button", { name: "Eine Ebene zurück", exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath("nested-mobile.png"), fullPage: true });
    await page.getByRole("button", { name: "Hauptkarte", exact: true }).click();
    await expect(page.locator("#atlas-map-select")).toHaveValue(rootId);
    // A scene opened directly must return to its actual ancestor, even if another atlas was remembered.
    const alternateSource = JSON.parse(await readFile(resolve("design/fixtures/eron/map-andaria.json"), "utf8"));
    alternateSource.mapImage = "Andere Hauptkarte.jpg";
    const alternate = await page.request.post(`${origin}/api/campaigns/${campaign.id}/maps/import`, { headers: { origin }, data: { json: JSON.stringify(alternateSource) } });
    expect(alternate.ok()).toBe(true);
    await page.goto(`${origin}/?campaign=${campaign.id}&stage=atlas&atlasMap=${(await alternate.json()).id}&atlasChild=${second}`);
    await expect(page.getByRole("navigation", { name: "Kartenpfad" }).locator("button[aria-current=page]")).toBeVisible();
    await page.getByRole("button", { name: "Hauptkarte", exact: true }).click();
    await expect(page.locator("#atlas-map-select")).toHaveValue(rootId);
    await page.goBack();
    await expect(page.getByRole("region", { name: "Unterkarte", exact: true })).toBeVisible();
    expect(new URL(page.url()).searchParams.get("atlasChild")).toBe(second);
    await expect(page.getByText(/konnte nicht/)).toHaveCount(0);
    expect(errors).toEqual([]);
  } finally { await context?.close(); await app?.close(); await db?.close(); }
});
