-- Library removal and replacement entrances are retained facts, not history mutations.
-- Existing sources, map revisions, entrance rows, sessions and receipts stay untouched.
CREATE TABLE map_lifecycle_events (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_id text NOT NULL UNIQUE, campaign_id text NOT NULL REFERENCES campaigns(id),
  actor_user_id text NOT NULL REFERENCES users(id),
  operation text NOT NULL CHECK(operation IN ('map.delete','map.enter','map.revise')),
  request_hash text NOT NULL CHECK(request_hash ~ '^[a-f0-9]{64}$'),
  request jsonb NOT NULL CHECK(jsonb_typeof(request)='object'),
  payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object'),
  ack jsonb NOT NULL CHECK(jsonb_typeof(ack)='object'),
  created_at bigint NOT NULL
);
-- statement
CREATE INDEX map_lifecycle_campaign ON map_lifecycle_events(campaign_id,seq);
-- statement
CREATE INDEX map_lifecycle_retired ON map_lifecycle_events USING gin ((payload->'preview'->'maps'))
  WHERE operation='map.delete';
-- statement
CREATE TRIGGER protect_map_lifecycle_events BEFORE UPDATE OR DELETE ON map_lifecycle_events
  FOR EACH ROW EXECUTE FUNCTION deny_history_mutation();
