-- Der Figurantrag ist ein eigenes Objekt. Eine Figur entsteht erst bei der Bestaetigung, ueber
-- denselben actor.instantiate-Befehl wie jede andere Figur; eine unbestaetigte Figur gibt es nie.
-- Deshalb bleiben authorizeActor und seine acht Aufrufer unveraendert, und keine eingefrorene
-- Tabelle wird angefasst. Additiv im Sinne von design/10 §1.4: alter Code kennt diese Tabellen
-- nicht und verhaelt sich unveraendert.

-- Die Freigabe macht eine Werkstattvorlage fuer Spieler waehlbar. Sie ist widerrufbar und traegt
-- ihre eigene Version, damit zwei Spielleitungen sich nicht gegenseitig ueberschreiben.
CREATE TABLE figurvorlagen_freigaben (
  template_id text PRIMARY KEY,
  campaign_id text NOT NULL REFERENCES campaigns(id),
  version integer NOT NULL DEFAULT 1 CHECK(version > 0),
  freed_by text NOT NULL REFERENCES users(id),
  freed_at bigint NOT NULL,
  revoked_at bigint,
  FOREIGN KEY(template_id,campaign_id) REFERENCES actor_templates(id,campaign_id)
);
-- statement
CREATE INDEX figurvorlagen_freigaben_offen ON figurvorlagen_freigaben(campaign_id) WHERE revoked_at IS NULL;
-- statement
-- Der Antrag selbst. Er bindet die Vorlagenrevision, nicht die Vorlage: eine Revision ist
-- unveraenderlich und inhaltsgehasht, „die jeweils neueste Fassung" waere ein Versprechen, das
-- sich zwischen Antrag und Bestaetigung aendern koennte.
CREATE TABLE figurantraege (
  id text PRIMARY KEY,
  campaign_id text NOT NULL REFERENCES campaigns(id),
  antragsteller text NOT NULL REFERENCES users(id),
  template_id text NOT NULL,
  template_revision integer NOT NULL CHECK(template_revision > 0),
  name text NOT NULL CHECK(length(name) BETWEEN 1 AND 160),
  anfangswerte jsonb NOT NULL CHECK(jsonb_typeof(anfangswerte)='object'),
  state text NOT NULL CHECK(state IN ('offen','bestaetigt','abgelehnt','zurueckgezogen')),
  reason text CHECK(reason IS NULL OR length(reason) BETWEEN 1 AND 500),
  version integer NOT NULL DEFAULT 1 CHECK(version > 0),
  created_at bigint NOT NULL,
  decided_by text REFERENCES users(id),
  decided_at bigint,
  actor_id text,
  -- Nur auf `users`, nicht auf die Mitgliedschaft: wer die Kampagne verlaesst, soll das koennen,
  -- ohne dass ein alter Antrag es verhindert. Die Rechtepruefung liegt in der Domain.
  FOREIGN KEY(template_id,campaign_id,template_revision) REFERENCES actor_template_revisions(template_id,campaign_id,revision),
  FOREIGN KEY(actor_id,campaign_id) REFERENCES actor_profiles(actor_id,campaign_id),
  CHECK((decided_by IS NULL) = (decided_at IS NULL)),
  -- Ein offener Antrag ist unentschieden; jeder andere Zustand nennt seine entscheidende Person.
  CHECK((state='offen') = (decided_by IS NULL)),
  -- Genau der bestaetigte Antrag hat eine Figur, und nur der abgelehnte hat einen Grund.
  CHECK((state='bestaetigt') = (actor_id IS NOT NULL)),
  CHECK((state='abgelehnt') OR reason IS NULL)
);
-- statement
CREATE INDEX figurantraege_kampagne ON figurantraege(campaign_id,state);
-- statement
CREATE INDEX figurantraege_antragsteller ON figurantraege(campaign_id,antragsteller);
-- statement
-- Ein OFFENER Antrag je Person und Vorlage. Zwei gleichzeitig offene Antraege derselben Person
-- auf dieselbe Vorlage sind ein Doppelklick, kein zweiter Wunsch — und sie zwaengen die
-- Spielleitung zu zwei Entscheidungen ueber dieselbe Sache. Nach Ruecknahme, Ablehnung oder
-- Bestaetigung ist der Weg wieder frei; entschiedene Antraege beschraenken nichts.
CREATE UNIQUE INDEX figurantraege_ein_offener ON figurantraege(campaign_id,antragsteller,template_id) WHERE state='offen';
-- statement
-- Jede Entscheidung hinterlaesst ihren Beleg: die urspruengliche Anfrage, ihr Hash und die
-- ausgelieferte Antwort. `command_id UNIQUE` macht einen Wiederholungsversuch zu derselben
-- Antwort statt zu einem zweiten Antrag.
CREATE TABLE figurantrag_events (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_id text NOT NULL UNIQUE,
  campaign_id text NOT NULL REFERENCES campaigns(id),
  actor_user_id text NOT NULL REFERENCES users(id),
  operation text NOT NULL CHECK(operation IN ('figurvorlage.freigeben','figurvorlage.entziehen',
    'figurantrag.beantragen','figurantrag.zuruecknehmen','figurantrag.bestaetigen','figurantrag.ablehnen')),
  request_hash text NOT NULL CHECK(request_hash ~ '^[a-f0-9]{64}$'),
  request jsonb NOT NULL CHECK(jsonb_typeof(request)='object'),
  payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object'),
  ack jsonb NOT NULL CHECK(jsonb_typeof(ack)='object'),
  created_at bigint NOT NULL
);
-- statement
CREATE INDEX figurantrag_events_kampagne ON figurantrag_events(campaign_id,seq);
-- statement
CREATE TRIGGER protect_figurantrag_events BEFORE UPDATE OR DELETE ON figurantrag_events
  FOR EACH ROW EXECUTE FUNCTION deny_history_mutation();
