// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Kaya Yesilyurt - Atlas Chronicles. Siehe LICENSE.
import { useCallback, useEffect, useState } from "react";
import type { ChronistPreviewBody, ChronistPreviewResult, ChronistProviderDescription, ChronistRunPage, ChronistRunView, ChronistSourceDescriptor, ChronistStartAck, ChronistSuggestionPage, StartChronistRunBody } from "@chronicle/protocol";
import { BookOpen, Check, Feather, Play, RefreshCw, Square } from "lucide-react";
import { Button, EmptyState, Loading, Notice } from "@chronicle/ui";
import { ApiError, errorText, type Campaign } from "../api";
import { useResource } from "../hooks";
import { chronistApi, chronistPath, chronistReason } from "./chronist-api";
import { CHRONIST_TASKS, DEFAULT_CHRONIST_BUDGET, chronistCost, chronistNumber, clearChronistDrafts, createChronistCommand, type ChronistMode } from "./chronist-model";
import { ChronistSources } from "./ChronistSources";
import { ChronistSessionNotes } from "./ChronistSessionNotes";
import { ChronistReview } from "./ChronistReview";
import "./chronist.css";

interface Finding { art: string; entryId: string; titel: string; text: string; passagen: readonly string[] }
const stateLabel = { running: "Auswertung läuft", paused: "Unterbrochen", partial: "Mit Teilergebnissen beendet", completed: "Bereit zur Durchsicht" };
const taskName = (mode: ChronistMode) => CHRONIST_TASKS.find(task => task.id === mode)!.title;
export function ChronistWorkbench({ campaign, onDirty, onOpenEntry, onClose, liveRevision = 0 }: {
  campaign: Campaign; onDirty: (dirty: boolean) => void; onOpenEntry: (id: string) => void; onClose: () => void; liveRevision?: number;
}) {
  const gm = campaign.role === "leitung", campaignId = campaign.id;
  const [view, setView] = useState<"prepare" | "review">("prepare"), [mode, setMode] = useState<ChronistMode>("prosa"), [revision, setRevision] = useState(0);
  const [sources, setSources] = useState<ChronistSourceDescriptor[]>([]), [sessionId, setSessionId] = useState(""), [savedEntryId, setSavedEntryId] = useState<string | null>(null);
  const [providerId, setProviderId] = useState(""), [chosenModel, setChosenModel] = useState(""), [budget, setBudget] = useState<ChronistPreviewResult["budget"]>({ ...DEFAULT_CHRONIST_BUDGET });
  const [prepared, setPrepared] = useState<{ request: ChronistPreviewBody; result: ChronistPreviewResult } | null>(null), [consent, setConsent] = useState(false);
  const [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [denied, setDenied] = useState(false);
  const [runId, setRunId] = useState<string | null>(null), [proposalId, setProposalId] = useState<string | null>(null), [runAfter, setRunAfter] = useState<string | null>(null), [suggestionAfter, setSuggestionAfter] = useState<string | null>(null);
  const providers = useResource<{ providers: readonly ChronistProviderDescription[] }>(gm ? chronistPath(campaignId, "/providers") : null, revision + liveRevision, 8000);
  const findings = useResource<readonly Finding[]>(chronistPath(campaignId), revision + liveRevision);
  const runs = useResource<ChronistRunPage>(gm && view === "review" ? chronistPath(campaignId, `/runs?limit=50${runAfter ? `&after=${encodeURIComponent(runAfter)}` : ""}`) : null, revision + liveRevision, 5000);
  const run = useResource<ChronistRunView>(gm && view === "review" && runId ? chronistPath(campaignId, `/runs/${encodeURIComponent(runId)}`) : null, revision + liveRevision, 2000);
  const suggestions = useResource<ChronistSuggestionPage>(view === "review" ? chronistPath(campaignId, `/suggestions?limit=50${runId ? `&runId=${encodeURIComponent(runId)}` : ""}${suggestionAfter ? `&after=${encodeURIComponent(suggestionAfter)}` : ""}`) : null, revision + liveRevision, 5000);
  const [startCommand] = useState(() => createChronistCommand<Omit<StartChronistRunBody, "commandId">, ChronistStartAck>(body => chronistApi(chronistPath(campaignId, "/runs"), { method: "POST", body })));
  const provider = providers.data?.providers.find(item => item.id === providerId) ?? (!providerId ? providers.data?.providers.find(item => item.location === "lokal" && item.available) ?? providers.data?.providers.find(item => item.location === "lokal") : undefined);
  const model = chosenModel || provider?.models[0] || "";
  const refresh = () => setRevision(value => value + 1);
  const changeDirty = useCallback((value: boolean) => { setDirty(value); onDirty(value); }, [onDirty]);
  const guard = () => !dirty || window.confirm("Ungespeicherte Änderungen verwerfen?");
  const invalidate = () => { setPrepared(null); setConsent(false); setError(""); };
  const locked = busy || !!startCommand.pending;
  useEffect(() => {
    if (gm && providers.error && !providers.data) { setSources([]); setPrepared(null); setConsent(false); try { clearChronistDrafts(sessionStorage, campaignId); } catch { /* No secondary cache. */ } }
  }, [providers.error, providers.data, gm, campaignId]);
  const execute = async (work: () => Promise<void>) => {
    setBusy(true); setError(""); setNotice("");
    try { await work(); }
    catch (cause) { setError(errorText(cause)); if (cause instanceof ApiError && [401, 403, 404].includes(cause.status)) { setDenied(true); setSources([]); setPrepared(null); try { clearChronistDrafts(sessionStorage, campaignId); } catch { /* No fallback cache. */ } } }
    finally { setBusy(false); }
  };
  const preview = () => execute(async () => {
    if (!provider) return;
    const request: ChronistPreviewBody = { mode, ...(mode === "sitzung" ? { sessionId } : {}), providerId: provider.id, model, sourceRefs: sources.map(source => source.ref), budget };
    const result = await chronistApi<ChronistPreviewResult>(chronistPath(campaignId, "/runs/preview"), { method: "POST", body: request });
    setPrepared({ request, result }); setConsent(false);
  });
  const start = () => execute(async () => {
    if (!prepared) return;
    const ack = await startCommand.send({ ...prepared.request, scopeHash: prepared.result.scopeHash, ...(prepared.result.provider.location === "fremd" ? { externalConsent: { scopeHash: prepared.result.scopeHash } } : {}) });
    setRunId(ack.runId); setView("review"); setSuggestionAfter(null); setPrepared(null); setConsent(false); refresh();
  });
  const changeView = (value: "prepare" | "review") => { if (value === view || !guard()) return; changeDirty(false); setProposalId(null); setView(value); };
  const openEntry = (id: string) => { onOpenEntry(id); };
  const chooseRun = (id: string | null) => { if (!guard()) return; changeDirty(false); setRunId(id); setProposalId(null); setSuggestionAfter(null); };
  return <section className="chronist-workbench" aria-label="Chronist">
    <header className="chronist-heading"><div className="chronist-heading-mark" aria-hidden="true"><Feather size={28} /></div><div><p className="eyebrow">Aus Geschichten wird eine Chronik</p><h2>Der Chronist</h2><p>Quellen durchsehen, Zusammenhänge entdecken, eure Geschichte weiterschreiben.</p></div><Button onClick={onClose}>Schließen</Button></header>
    <div className="chronist-view-tabs" aria-label="Chronist-Arbeitsbereiche"><Button aria-pressed={view === "prepare"} onClick={() => changeView("prepare")}>{gm ? "Neue Aufgabe" : "Regelbefunde"}</Button><Button aria-pressed={view === "review"} onClick={() => changeView("review")}>{gm ? "Läufe & Durchsicht" : "Vorschläge durchsehen"}</Button><Button aria-label="Chronist aktualisieren" onClick={refresh}><RefreshCw size={16} /></Button></div>
    {denied || gm && providers.error && !providers.data ? <Notice error>{error || providers.error || "Der Chronist ist für diesen Zugang nicht verfügbar."}<Button onClick={() => { setDenied(false); refresh(); }}>Zugang erneut prüfen</Button></Notice> : <>
      {error ? <Notice error>{error}<Button disabled={busy} onClick={refresh}>Stand aktualisieren</Button></Notice> : null}{notice ? <Notice>{notice}</Notice> : null}
      {view === "prepare" ? <>
        {gm ? <><div className="chronist-tasks" aria-label="Aufgabe wählen">{CHRONIST_TASKS.map((task, i) => <button key={task.id} className={mode === task.id ? "chronist-task active" : "chronist-task"} aria-pressed={mode === task.id} disabled={locked} onClick={() => { if (mode === task.id || !guard()) return; changeDirty(false); setMode(task.id); invalidate(); }}><span className="chronist-task-number">0{i + 1}</span><strong>{task.title}</strong><span>{task.description}</span>{mode === task.id ? <Check size={16} aria-label="Ausgewählt" /> : null}</button>)}</div>
          <ol className="chronist-steps" aria-label="Aufgabenfolge"><li aria-current={!prepared ? "step" : undefined}><span>1</span> Quellen wählen</li><li aria-current={prepared ? "step" : undefined}><span>2</span> Umfang prüfen</li><li><span>3</span> Vorschläge durchsehen</li></ol>
          <section className="chronist-panel"><div className="section-heading"><div><p className="eyebrow">Schritt 1</p><h3>{mode === "sitzung" ? "Notizen speichern und Quellen wählen" : "Welche Quellen sollen gelesen werden?"}</h3></div><BookOpen size={21} aria-hidden="true" /></div>
            {mode === "sitzung" ? <ChronistSessionNotes campaignId={campaignId} sessionId={sessionId} onSession={id => { setSessionId(id); invalidate(); }} onSaved={id => { setSavedEntryId(id); refresh(); invalidate(); setNotice("Sitzungsnotiz gespeichert. Wähle jetzt ihre Passagen als Quellen aus."); }} onDirty={changeDirty} disabled={locked} /> : null}
            <ChronistSources campaignId={campaignId} selected={sources} onChange={value => { setSources(value); invalidate(); }} savedEntryId={savedEntryId} revision={revision + liveRevision} disabled={locked} />
          </section>
          <section className="chronist-panel" aria-label="Anbieter und Umfang"><p className="eyebrow">Schritt 2</p><h3>Anbieter und Umfang prüfen</h3><p className="field-help">Jede Aufgabe beginnt mit dem Regelwerk. Modellunterstützung ergänzt nur die ausgewählten Quellen.</p>
            {providers.loading ? <Loading text="Anbieter werden geprüft …" /> : <><div className="chronist-form-row"><label>Anbieter<select value={provider?.id ?? ""} disabled={locked} onChange={event => { setProviderId(event.target.value); setChosenModel(""); invalidate(); }}><option value="">Anbieter wählen …</option>{providers.data?.providers.map(item => <option key={item.id} value={item.id}>{item.label} · {item.location === "lokal" ? "Lokal" : "Extern"}{!item.available ? " · noch nicht bereit" : ""}</option>)}</select></label><label>Modell<select value={model} disabled={locked || !provider?.models.length} onChange={event => { setChosenModel(event.target.value); invalidate(); }}>{!model ? <option value="">Kein Modell verfügbar</option> : null}{provider?.models.map(name => <option key={name} value={name}>{name}</option>)}</select></label></div>
              {!provider?.available ? <Notice>{provider?.availabilityCode === "capability-unverified" ? "Dieser Anbieter ist für die benötigte Textauswertung noch nicht freigegeben." : "Hier ist noch kein einsatzbereiter lokaler Anbieter eingerichtet. Die Regelbefunde unten bleiben nutzbar."}</Notice> : <p className="chronist-provider-location">{provider.location === "lokal" ? "Lokale Verarbeitung · kein automatischer Wechsel zu einem externen Anbieter" : "Externe Verarbeitung · deine ausdrückliche Freigabe ist für jeden Lauf erforderlich"}</p>}
              <details className="chronist-setup"><summary>Anbieter einrichten</summary><p>Die Einrichtung erfolgt auf dem Rechner, der eure Kampagne bereitstellt. Dort wird ein lokaler Modellserver oder ein unterstützter externer Anbieter mit seinem Modell konfiguriert. Zugangsschlüssel bleiben auf diesem Rechner.</p><p>Nach der Einrichtung kannst du die Verfügbarkeit hier erneut prüfen. Die Liste zeigt ausschließlich die für diesen Host eingerichteten Anbieter.</p><Button onClick={refresh} disabled={busy}>Verfügbarkeit neu prüfen</Button></details>
            </>}
            <details className="chronist-budget"><summary>Grenzen der Auswertung anpassen</summary><div className="chronist-form-row"><label>Höchstens so viele Modellaufrufe<input type="number" min={0} max={128} value={budget.maxCalls} disabled={locked} onChange={event => { setBudget(value => ({ ...value, maxCalls: Math.max(0, Math.min(128, Number(event.target.value))) })); invalidate(); }} /></label><label>Höchstens so viele Eingabezeichen<input type="number" min={0} max={4_000_000} step={1000} value={budget.maxInputChars} disabled={locked} onChange={event => { setBudget(value => ({ ...value, maxInputChars: Math.max(0, Math.min(4_000_000, Number(event.target.value))) })); invalidate(); }} /></label><label>Höchstens so viele Ausgabezeichen<input type="number" min={0} max={512_000} step={1000} value={budget.maxOutputChars} disabled={locked} onChange={event => { setBudget(value => ({ ...value, maxOutputChars: Math.max(0, Math.min(512_000, Number(event.target.value))) })); invalidate(); }} /></label></div><p className="field-help">Die Grenzen zählen den gesamten Lauf einschließlich Wiederholungen. Eine Fortsetzung beginnt die Zählung nicht neu. Bei 0 Modellaufrufen wird ausschließlich das Regelwerk verwendet.</p></details>
            <Button variant="primary" disabled={locked || dirty || !sources.length || !provider || !model || mode === "sitzung" && !sessionId} onClick={() => void preview()}>{busy ? "Umfang wird geprüft …" : "Umfang und Kosten vorschauen"}</Button>{dirty ? <p className="field-help">Speichere zuerst deine Sitzungsnotiz.</p> : null}
            {prepared ? <div className="chronist-preview" role="region" aria-label="Vorschau der Auswertung"><h4>Das wird ausgewertet</h4><dl className="chronist-metrics"><div><dt>Quellen</dt><dd>{prepared.result.sources.length} Passagen</dd></div><div><dt>Quelltext</dt><dd>{chronistNumber(prepared.result.sourceChars)} Zeichen</dd></div><div><dt>Modellarbeit</dt><dd>bis zu {Math.min(prepared.result.maxCalls, prepared.result.budget.maxCalls)} Aufrufe</dd></div><div><dt>Kostenschätzung</dt><dd>{chronistCost(prepared.result.estimate.costMicros, prepared.result.estimate.currency)}</dd></div></dl><p className="field-help">Bis zu {chronistNumber(prepared.result.estimate.inputChars)} Eingabezeichen einschließlich Anweisungen; bis zu {chronistNumber(prepared.result.estimate.outputChars)} Ausgabezeichen. {prepared.result.estimate.costMicros === null ? "Die Kosten lassen sich für diesen Lauf noch nicht verlässlich schätzen. Das bedeutet nicht, dass die Auswertung kostenlos ist." : "Der tatsächliche Verbrauch kann abweichen."}</p>
              <div className="chronist-preview-sources">{prepared.result.sources.map((source, index) => <details key={source.sourceId}><summary>{source.title} · Passage {index + 1} · {chronistNumber(source.text.length)} Zeichen</summary><p className="chronist-source-text">{source.text}</p></details>)}</div>
              {prepared.result.ruleFindings.length ? <div className="chronist-preview-findings"><h4>Bereits im Regelwerk gefunden</h4>{prepared.result.ruleFindings.map((finding, i) => <p key={i}><strong>{finding.titel}</strong> · {finding.text}</p>)}</div> : null}{prepared.result.warnings.map((warning, i) => <Notice key={i}>{chronistReason(warning)}</Notice>)}
              {prepared.result.provider.location === "fremd" ? <label className="chronist-consent chronist-check"><input type="checkbox" checked={consent} disabled={locked} onChange={event => setConsent(event.target.checked)} /><span>Ich gebe diese {prepared.result.sources.length} Passagen und den angezeigten Umfang für diesen Lauf an {prepared.result.provider.label} ({prepared.result.model}) frei.{prepared.result.estimate.costMicros === null ? " Die Kosten sind unbekannt." : ""}</span></label> : null}
              {!prepared.result.provider.available ? <Notice>Du kannst das Regelwerk jetzt ausführen. Die Modellarbeit pausiert, bis dieser Anbieter eingerichtet ist; vorhandene Regelvorschläge bleiben zur Durchsicht erhalten.</Notice> : null}
              <Button variant="primary" disabled={busy || prepared.result.provider.location === "fremd" && !consent} onClick={() => void start()}><Play size={16} />{startCommand.pending ? "Start unverändert erneut versuchen" : "Auswertung starten"}</Button>
            </div> : null}
          </section></> : null}
        <section className="chronist-panel" aria-label="Regelbefunde"><p className="eyebrow">Ohne Modell nutzbar</p><h3>Was das Regelwerk schon erkennt</h3>{findings.loading ? <Loading text="Regelbefunde werden gelesen …" /> : findings.error ? <Notice error>{findings.error}</Notice> : findings.data?.length ? <ul className="chronist-findings">{findings.data.map((finding, i) => <li key={`${finding.entryId}:${i}`}><div><strong>{finding.titel}</strong><p>{finding.text}</p></div><Button onClick={() => openEntry(finding.entryId)}>Artikel öffnen</Button></li>)}</ul> : <p className="field-help">Im lesbaren Bestand wurden keine widersprüchlichen Jahresangaben oder unlesbaren Datumsfelder gefunden.</p>}</section>
      </> : <>
        {gm ? <section className="chronist-panel"><div className="section-heading"><h3>Deine Auswertungen</h3><Button aria-pressed={runId === null} onClick={() => chooseRun(null)}>Alle Vorschläge</Button></div>{runs.loading ? <Loading text="Läufe werden geladen …" /> : runs.error ? <Notice error>{runs.error}</Notice> : runs.data?.runs.length ? <div className="chronist-run-list">{runs.data.runs.map(item => <button key={item.runId} className={item.runId === runId ? "chronist-run selected" : "chronist-run"} aria-pressed={item.runId === runId} onClick={() => chooseRun(item.runId)}><strong>{taskName(item.mode)}</strong><span>{new Date(item.createdAt).toLocaleString("de-DE")}</span><span>{stateLabel[item.state]}</span><small>{item.provider.label} · {item.progress.suggestions} Vorschläge</small></button>)}</div> : <p className="field-help">Noch keine Auswertung gestartet. Wähle unter „Neue Aufgabe“ deine Quellen.</p>}<div className="button-row">{runAfter ? <Button onClick={() => setRunAfter(null)}>Erste Laufseite</Button> : null}{runs.data && !runs.data.complete && runs.data.after ? <Button onClick={() => setRunAfter(runs.data!.after)}>Weitere Läufe</Button> : null}</div>
          {run.loading ? <Loading text="Laufstand wird geprüft …" /> : run.error ? <Notice error>{run.error}</Notice> : run.data ? <ChronistRun key={`${run.data.runId}:${run.data.version}`} run={run.data} busy={busy} onCancel={() => void execute(async () => { await chronistApi(chronistPath(campaignId, `/runs/${encodeURIComponent(run.data!.runId)}/cancel`), { method: "POST", body: { expectedVersion: run.data!.version } }); refresh(); })} onResume={(external, unknown) => void execute(async () => { const value = run.data!; await chronistApi(chronistPath(campaignId, `/runs/${encodeURIComponent(value.runId)}/resume`), { method: "POST", body: { expectedVersion: value.version, scopeHash: value.scopeHash, ...(external ? { externalConsent: { scopeHash: value.scopeHash } } : {}), ...(unknown ? { acknowledgeUnknownOutcome: true } : {}) } }); refresh(); })} /> : null}
        </section> : null}
        {proposalId ? <ChronistReview key={proposalId} campaignId={campaignId} proposalId={proposalId} gm={gm} onDirty={changeDirty} onChanged={refresh} onOpenEntry={openEntry} onClose={() => { if (guard()) { setProposalId(null); changeDirty(false); } }} /> : <section className="chronist-panel" aria-label="Vorschlagsstapel"><p className="eyebrow">Schritt 3</p><h3>Vorschläge durchsehen</h3><p className="field-help">Prüfe die Quellen und bearbeite den Entwurf. Deine Einreichung ist ein Antrag; sie wird erst durch die reguläre Ratifikation zu Kanon.</p>{suggestions.loading ? <Loading text="Sichtbare Vorschläge werden geladen …" /> : suggestions.error ? <Notice error>{suggestions.error}</Notice> : suggestions.data?.suggestions.length ? <div className="chronist-suggestion-list">{suggestions.data.suggestions.map(suggestion => <button key={suggestion.id} onClick={() => setProposalId(suggestion.id)} className="chronist-suggestion"><span className="eyebrow">{suggestion.origin === "regelwerk" ? "Regelwerk" : "Modellvorschlag"}</span><strong>{suggestion.kind === "abriss" ? "Erzählerischer Abriss" : suggestion.kind === "ereignis" ? "Ereignis" : suggestion.kind === "widerspruch" ? "Widerspruch" : "Offene Datierung"}</strong><span>{[...new Set(suggestion.sources.map(source => source.title))].join(" · ")}</span><small>{suggestion.stale ? "Ältere Quellen · " : ""}{suggestion.state === "offen" ? "Zur Durchsicht" : suggestion.state === "eingereicht" ? "Als Antrag eingereicht" : "Verworfen"}</small></button>)}</div> : <EmptyState title={run.data?.state === "running" ? "Die ersten Vorschläge entstehen." : "Dieser Stapel ist leer."}>{run.data?.state === "running" ? "Du kannst den Laufstand oben verfolgen. Neue belegte Vorschläge erscheinen hier automatisch." : "Hier erscheinen die für deinen Wissensblick verfügbaren Vorschläge. Eine Auswertung kann auch ohne neue Vorschläge enden."}</EmptyState>}<div className="button-row">{suggestionAfter ? <Button onClick={() => setSuggestionAfter(null)}>Erste Vorschlagsseite</Button> : null}{suggestions.data && !suggestions.data.complete && suggestions.data.after ? <Button onClick={() => setSuggestionAfter(suggestions.data!.after)}>Weitere Vorschläge</Button> : null}</div></section>}
      </>}
    </>}
  </section>;
}

function ChronistRun({ run, busy, onCancel, onResume }: { run: ChronistRunView; busy: boolean; onCancel: () => void; onResume: (external: boolean, unknown: boolean) => void }) {
  const [externalConsent, setExternalConsent] = useState(false), [unknownConsent, setUnknownConsent] = useState(false);
  const external = run.provider.location === "fremd", unknown = run.stopReason === "outcome-unknown" || run.unknownCalls > 0;
  return <section className="chronist-run-detail" aria-label="Laufstand"><div className="section-heading"><h4 aria-live="polite">{stateLabel[run.state]}</h4>{run.actions.includes("cancel") ? <Button variant="danger" disabled={busy || run.cancelRequested} onClick={onCancel}><Square size={14} />{run.cancelRequested ? "Abbruch angefordert" : "Auswertung abbrechen"}</Button> : null}</div>
    <p>{run.provider.label} · {run.model}</p><progress value={run.usage.calls} max={Math.max(1, run.budget.maxCalls)} aria-label="Gegen die Grenze gezählte Modellaufrufe" /><p className="field-help">{run.usage.calls} von höchstens {run.budget.maxCalls} reservierten Modellaufrufen · {run.progress.suggestions} Vorschläge · {run.progress.rejections} Beiträge ohne ausreichenden Beleg verworfen</p>
    {run.stopReason ? <Notice>{chronistReason(run.stopReason)}</Notice> : null}<dl className="chronist-metrics"><div><dt>Eingabebudget belegt</dt><dd>{chronistNumber(run.usage.inputChars)} Zeichen</dd></div><div><dt>Ausgabe erfasst</dt><dd>{chronistNumber(run.usage.outputChars)} Zeichen</dd></div><div><dt>Ausgabe noch gebunden</dt><dd>{chronistNumber(run.usage.reservedOutputChars)} Zeichen</dd></div><div><dt>Erfasster Kostenstand</dt><dd>{chronistCost(run.usage.costMicros, run.usage.currency)}</dd></div></dl><p className="field-help">Verbleibende Grenzen: {Math.max(0, run.budget.maxCalls - run.usage.calls)} Aufrufe · {chronistNumber(Math.max(0, run.budget.maxInputChars - run.usage.inputChars))} Eingabezeichen · {chronistNumber(Math.max(0, run.budget.maxOutputChars - run.usage.outputChars - run.usage.reservedOutputChars))} Ausgabezeichen.</p>
    <p className="field-help">Kosten beruhen auf Anbieterangaben oder dem hinterlegten Tarif. {run.usage.inputTokens === null || run.usage.outputTokens === null ? "Tokenverbrauch unbekannt." : `${chronistNumber(run.usage.inputTokens)} Eingabetokens · ${chronistNumber(run.usage.outputTokens)} Ausgabetokens.`} {!run.usage.tokensComplete ? "Die Tokenangaben sind noch unvollständig. " : ""}{!run.usage.costComplete ? "Die Kosten sind noch unvollständig; bereits gesendete Aufrufe können nachträglich abgerechnet werden." : ""}</p>
    <details className="chronist-run-sources"><summary>{run.sources.length} ausgewählte Quellpassagen dieses Laufs</summary>{run.sources.map((source, i) => <details key={source.sourceId}><summary>{source.title} · Passage {i + 1}</summary><p className="chronist-source-text">{source.text}</p></details>)}</details>
    {run.unknownCalls > 0 ? <Notice>{run.unknownCalls} gesendete Aufrufe haben einen ungewissen Ausgang. Ihre gebundene Ausgabe und mögliche Kosten bleiben berücksichtigt.</Notice> : null}
    {run.actions.includes("resume") ? <div className="chronist-resume"><h4>Auswertung fortsetzen</h4>{external ? <label className="chronist-consent chronist-check"><input type="checkbox" checked={externalConsent} onChange={event => setExternalConsent(event.target.checked)} /><span>Ich gebe die oben gezeigten {run.sources.length} unveränderten Quellpassagen dieses Laufs erneut für {run.provider.label} ({run.model}) frei. Bisheriger Verbrauch und Grenzen gelten weiter.{run.provider.pricing === null ? " Die Kosten weiterer Aufrufe sind unbekannt." : ""}</span></label> : null}{unknown ? <label className="chronist-consent chronist-check"><input type="checkbox" checked={unknownConsent} onChange={event => setUnknownConsent(event.target.checked)} /><span>Ich habe den ungewissen Ausgang gelesen. Bereits gesendete Aufrufe können Kosten verursacht haben; eine Fortsetzung kann weitere Kosten erzeugen.</span></label> : null}<Button variant="primary" disabled={busy || external && !externalConsent || unknown && !unknownConsent} onClick={() => onResume(externalConsent, unknownConsent)}>Auswertung fortsetzen</Button></div> : null}
  </section>;
}
