// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Kaya Yesilyurt - Atlas Chronicles. Siehe LICENSE.
import { useEffect, useRef, useState } from "react";
import { Button, Loading, Notice } from "@chronicle/ui";
import { PUBLIC_MINT_KINDS, type AuthoringAck, type EntryPublication, type EntryPublishPreviewInput, type PublicationConfigureInput, type PublicationPolicy, type PublicationRoute, type ThemeCard } from "@chronicle/protocol";
import { api, apiPath, plainText, type Campaign, type EntrySummary, type HistoryItem } from "../api";
import { useResource, useTask } from "../hooks";
import { locale, t } from "../i18n";
import { useCommand, type MintReceipt } from "./game-api";

type Settings = { policy: PublicationPolicy | null; deliveryEnabled: boolean };
type PolicyDraft = Omit<PublicationConfigureInput, "commandId" | "expectedVersion">;
const slugFor = (text: string) => text.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 200) || "welt";
const warningLines = (text: string) => [...new Set(text.split("\n").map(line => line.trim()).filter(Boolean))];
const fromPolicy = (policy: PublicationPolicy | null, name: string): PolicyDraft => policy ? { enabled: policy.enabled, worldSlug: policy.worldSlug, title: policy.title, description: policy.description, locale: policy.locale, contentWarnings: policy.contentWarnings, theme: policy.theme } : { enabled: false, worldSlug: slugFor(name), title: name, description: "", locale: "de", contentWarnings: [], theme: null };

export function PublicationWorkbench({ campaign, liveRevision, onDirty }: { campaign: Campaign; liveRevision: number; onDirty: (dirty: boolean) => void }) {
  const [revision, setRevision] = useState(0), [section, setSection] = useState<"world" | "articles" | "routes">("world"), [dirty, setDirty] = useState(false);
  const settings = useResource<Settings>(apiPath(campaign.id, "/publication"), revision + liveRevision), themes = useResource<ThemeCard[]>(apiPath(campaign.id, "/themes"), revision + liveRevision);
  const refresh = () => setRevision(value => value + 1);
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty, onDirty]);
  const choose = (next: typeof section) => { if (next !== section && (!dirty || window.confirm(t("Ungespeicherte Veröffentlichungsauswahl verwerfen?")))) { setDirty(false); setSection(next); } };
  return <section className="authoring-workbench"><header><p className="eyebrow">{t("Ausgewählte Geschichten teilen")}</p><h1>{t("Veröffentlichung")}</h1><p>{t("Du gibst einen geprüften Artikelstand mit ausgewählten Passagen frei. Spätere private Änderungen erscheinen erst nach einer erneuten Veröffentlichung.")}</p></header>
    {settings.error ? <Notice error>{settings.error} <Button onClick={refresh}>{t("Erneut laden")}</Button></Notice> : null}
    {!settings.data ? settings.loading ? <Loading /> : null : <>
      {!settings.data.deliveryEnabled ? <Notice>{t("Die öffentliche Auslieferung ist auf diesem Server ausgeschaltet. Du kannst Veröffentlichungsstände vorbereiten und ihre Vorschau prüfen.")}</Notice> : null}
      <nav className="button-row" aria-label={t("Veröffentlichung bearbeiten")}>{([["world", t("Welt")], ["articles", t("Artikel")], ["routes", t("Adressen")]] as const).map(([id, label]) => <Button key={id} aria-current={section === id ? "page" : undefined} onClick={() => choose(id)}>{label}</Button>)}</nav>
      {section === "world" ? <WorldSettings campaign={campaign} settings={settings.data} themes={themes.data ?? []} onDirty={setDirty} onChanged={refresh} /> : !settings.data.policy ? <Notice>{t("Speichere zuerst die Welt-Einstellungen. Die Freigabe kann dabei ausgeschaltet bleiben.")}</Notice> : section === "articles" ? <ArticlePublisher liveRevision={revision + liveRevision} campaignId={campaign.id} policy={settings.data.policy} deliveryEnabled={settings.data.deliveryEnabled} onDirty={setDirty} onChanged={refresh} /> : <PublicationRoutes campaignId={campaign.id} policy={settings.data.policy} onDirty={setDirty} onChanged={refresh} revision={revision + liveRevision} />}
    </>}
  </section>;
}

function WorldSettings({ campaign, settings, themes, onDirty, onChanged }: { campaign: Campaign; settings: Settings; themes: ThemeCard[]; onDirty: (dirty: boolean) => void; onChanged: () => void }) {
  const [baseline, setBaseline] = useState(settings.policy), [draft, setDraft] = useState(() => fromPolicy(settings.policy, campaign.name)), [notice, setNotice] = useState("");
  const task = useTask(), command = useCommand();
  const dirty = JSON.stringify(draft) !== JSON.stringify(fromPolicy(baseline, campaign.name));
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty, onDirty]);
  const reload = () => { if (!dirty || window.confirm(t("Welt-Einstellungen verwerfen und den gespeicherten Stand laden?"))) { setBaseline(settings.policy); setDraft(fromPolicy(settings.policy, campaign.name)); setNotice(""); } };
  return <form className="panel" onSubmit={event => { event.preventDefault(); void task.run(async () => {
    const ack = await command<AuthoringAck>(apiPath(campaign.id, "/publication"), { ...draft, expectedVersion: baseline?.version ?? 0 }, "PUT");
    setBaseline({ ...draft, publicKey: baseline?.publicKey ?? "", version: ack.version }); setNotice(t("Welt-Einstellungen gespeichert.")); onChanged();
  }); }}><h2>{t("Öffentliche Welt")}</h2>{task.error ? <Notice error>{task.error}</Notice> : null}{notice ? <Notice>{notice}</Notice> : null}
    {settings.policy?.version !== baseline?.version ? <Notice>{t("Es liegt ein anderer gespeicherter Stand vor.")} <Button disabled={task.busy} onClick={reload}>{t("Gespeicherten Stand übernehmen")}</Button></Notice> : null}
    <fieldset disabled={task.busy} className="authoring-controls"><div className="rule-fields"><label>{t("Öffentlicher Titel")}<input required maxLength={200} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label>{t("Welt-Adresse")}<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={200} value={draft.worldSlug} onChange={e => setDraft({ ...draft, worldSlug: e.target.value })} /></label><label>{t("Sprache")}<select aria-label={t("Sprache")} value={draft.locale} onChange={e => setDraft({ ...draft, locale: e.target.value as "de" | "en" })}>{/* Sprachnamen in ihrer eigenen Sprache: die Angabe benennt die Sprache der veröffentlichten Welt, nicht die der Oberfläche. */}<option value="de">Deutsch</option><option value="en">English</option></select></label>
      <label>{t("Öffentliches Theme")}<select aria-label={t("Öffentliches Theme")} value={draft.theme ? `${draft.theme.themeId}:${draft.theme.revision}` : "default"} onChange={e => { const card = themes.find(card => `${card.id}:${card.revision}` === e.target.value); setDraft({ ...draft, theme: card ? { themeId: card.id, revision: card.revision } : null }); }}><option value="default">{t("Feste Vorlage Fantasy")}</option>{draft.theme && !themes.some(card => card.id === draft.theme!.themeId && card.revision === draft.theme!.revision) ? <option value={`${draft.theme.themeId}:${draft.theme.revision}`}>{t("Bisherige feste Revision {nummer}", { nummer: draft.theme.revision })}</option> : null}{themes.map(card => <option key={card.id} value={`${card.id}:${card.revision}`}>{t("{name} · Revision {nummer}", { name: card.manifest.name, nummer: card.revision })}</option>)}</select></label></div>
      <label>{t("Beschreibung")}<textarea maxLength={2000} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label>{t("Inhaltshinweise, ein Hinweis je Zeile")}<textarea value={draft.contentWarnings.join("\n")} onChange={e => setDraft({ ...draft, contentWarnings: e.target.value.split("\n") })} onBlur={() => setDraft({ ...draft, contentWarnings: warningLines(draft.contentWarnings.join("\n")) })} /></label>
      <label className="check-label"><input type="checkbox" checked={draft.enabled} onChange={e => setDraft({ ...draft, enabled: e.target.checked })} /> {t("Welt ausdrücklich freigeben. Bei eingeschalteter Server-Auslieferung sind ihre freigegebenen Artikel ohne Anmeldung lesbar.")}</label>
      <Button type="submit" variant="primary">{t("Welt-Einstellungen speichern")}</Button>
    </fieldset>{settings.policy?.enabled && settings.deliveryEnabled ? <p><a href={`/w/${encodeURIComponent(settings.policy.publicKey)}/${encodeURIComponent(settings.policy.worldSlug)}`} target="_blank" rel="noreferrer">{t("Öffentliche Welt öffnen")}</a></p> : null}
  </form>;
}

function ArticlePublisher({ campaignId, liveRevision, policy, deliveryEnabled, onDirty, onChanged }: { campaignId: string; liveRevision: number; policy: PublicationPolicy; deliveryEnabled: boolean; onDirty: (dirty: boolean) => void; onChanged: () => void }) {
  const [entryId, setEntryId] = useState(""), [dirty, setDirty] = useState(false), [revision, setRevision] = useState(0);
  const entries = useResource<EntrySummary[]>(apiPath(campaignId, "/entries"), revision + liveRevision);
  const history = useResource<HistoryItem[]>(entryId ? apiPath(campaignId, `/entries/${encodeURIComponent(entryId)}/history`) : null, revision + liveRevision);
  const published = useResource<EntryPublication>(entryId ? apiPath(campaignId, `/entries/${encodeURIComponent(entryId)}/publication`) : null, revision + liveRevision);
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty, onDirty]);
  const refresh = () => { setRevision(value => value + 1); onChanged(); };
  return <section><label>{t("Artikel auswählen")}<select aria-label={t("Artikel auswählen")} value={entryId} onChange={e => { if (!dirty || window.confirm(t("Ungespeicherte Veröffentlichungsauswahl verwerfen?"))) { setEntryId(e.target.value); setDirty(false); } }}><option value="">{t("Artikel wählen")}</option>{entries.data?.map(entry => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label>
    {entries.error || history.error || published.error ? <Notice error>{entries.error || history.error || published.error} <Button onClick={refresh}>{t("Erneut laden")}</Button></Notice> : null}
    {history.loading || published.loading ? <Loading /> : null}
    {entryId && history.data?.[0] && published.loaded ? <PublishSelection key={entryId} campaignId={campaignId} entryId={entryId} latest={history.data[0]} published={published.data} policy={policy} deliveryEnabled={deliveryEnabled} onDirty={setDirty} onChanged={refresh} /> : null}
  </section>;
}

function PublishSelection({ campaignId, entryId, latest, published, policy, deliveryEnabled, onDirty, onChanged }: { campaignId: string; entryId: string; latest: HistoryItem; published: EntryPublication | null; policy: PublicationPolicy; deliveryEnabled: boolean; onDirty: (dirty: boolean) => void; onChanged: () => void }) {
  const [source, setSource] = useState(latest), [version, setVersion] = useState(published?.version ?? 0);
  const [selected, setSelected] = useState(() => published?.revisionId === latest.id ? published.passageIds : []), [slug, setSlug] = useState(published?.publicSlug ?? slugFor(latest.document.slug)), [warnings, setWarnings] = useState(published?.metadata.contentWarnings.join("\n") ?? ""), [mintIds, setMintIds] = useState<string[]>([]);
  const [dirty, setDirty] = useState(false), [preview, setPreview] = useState<{ request: EntryPublishPreviewInput; html: string } | null>(null), [notice, setNotice] = useState("");
  const task = useTask(), command = useCommand(), alive = useRef(true), previewEpoch = useRef(0);
  useEffect(() => { alive.current = true; return () => { alive.current = false; previewEpoch.current++; }; }, []);
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty, onDirty]);
  const request: EntryPublishPreviewInput = { expectedArticleRevisionId: source.id, expectedPublicationVersion: version, expectedPolicyVersion: policy.version, passageIds: selected, publicSlug: slug, contentWarnings: warningLines(warnings), mintIds };
  const reviewed = preview && JSON.stringify(preview.request) === JSON.stringify(request);
  const changed = () => { previewEpoch.current++; setPreview(null); setDirty(true); setNotice(""); };
  const loadLatest = () => { if (!dirty || window.confirm(t("Auswahl verwerfen und den aktuellen Artikelstand laden?"))) { setSource(latest); setVersion(published?.version ?? 0); setSelected(published?.revisionId === latest.id ? published.passageIds : []); setMintIds([]); setSlug(published?.publicSlug ?? slugFor(latest.document.slug)); setWarnings(published?.metadata.contentWarnings.join("\n") ?? ""); setDirty(false); setPreview(null); previewEpoch.current++; } };
  return <section className="panel"><h2>{source.document.title}</h2><p>{t("Artikelstand {nummer}.", { nummer: source.seq })} {published?.enabled ? t("Ein Stand ist bereits freigegeben.") : t("Dieser Artikel ist nicht freigegeben.")}</p>
    {task.error ? <Notice error>{task.error}</Notice> : null}{notice ? <Notice>{notice}</Notice> : null}
    {source.id !== latest.id || version !== (published?.version ?? 0) ? <Notice>{t("Der gespeicherte Artikel oder seine Veröffentlichung hat sich geändert.")} <Button disabled={task.busy} onClick={loadLatest}>{t("Aktuellen Stand laden")}</Button></Notice> : null}
    <fieldset disabled={task.busy} className="authoring-controls"><label>{t("Öffentliche Artikeladresse")}<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={200} value={slug} onChange={e => { setSlug(e.target.value); changed(); }} /></label><label>{t("Inhaltshinweise, ein Hinweis je Zeile")}<textarea value={warnings} onChange={e => { setWarnings(e.target.value); changed(); }} /></label>
      <h3>{t("Passagen ausdrücklich auswählen")}</h3>{source.document.passagen.map(passage => <article key={passage.pid} className="publication-passage"><label className="check-label"><input type="checkbox" checked={selected.includes(passage.pid)} onChange={e => { setSelected(e.target.checked ? [...selected, passage.pid].sort() : selected.filter(pid => pid !== passage.pid)); setMintIds([]); changed(); }} /><span>{passage.pfad.join(" › ") || t("Passage {nummer}", { nummer: passage.ord + 1 })}</span></label><p>{plainText(passage.inhalt)}</p>{selected.includes(passage.pid) ? <MintChoices campaignId={campaignId} passageId={passage.pid} selected={mintIds} onChange={ids => { setMintIds(ids); changed(); }} /> : null}</article>)}
      <Button disabled={!selected.length || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)} onClick={() => { const epoch = ++previewEpoch.current; void task.run(async () => { const result = await api<{ html: string }>(apiPath(campaignId, `/entries/${encodeURIComponent(entryId)}/publication/preview`), { method: "POST", body: request }); if (alive.current && previewEpoch.current === epoch) setPreview({ request, html: result.html }); }); }}>{t("Öffentliche Vorschau prüfen")}</Button>
    </fieldset>
    {preview ? <section><h3>{t("So wird dieser Stand öffentlich gelesen")}</h3><iframe title={t("Öffentliche Artikelvorschau")} className="publication-preview" sandbox="" referrerPolicy="no-referrer" srcDoc={preview.html} /><p>{t("Prüfe auch Inhaltshinweise, Quellen und die freigegebenen Belege in der Vorschau.")}</p><Button variant="primary" disabled={task.busy || !reviewed} onClick={() => { if (!reviewed || !preview) return; void task.run(async () => { const ack = await command<AuthoringAck>(apiPath(campaignId, `/entries/${encodeURIComponent(entryId)}/publication`), preview.request, "PUT"); if (alive.current) { setVersion(ack.version); setDirty(false); setPreview(null); setNotice(policy.enabled && deliveryEnabled ? t("Der geprüfte Artikelstand ist jetzt öffentlich.") : t("Der geprüfte Artikelstand ist gespeichert. Er wird erst bei freigegebener Welt und aktiver Server-Auslieferung öffentlich.")); onChanged(); } }); }}>{t("Genau diesen geprüften Stand freigeben")}</Button></section> : null}
    {published?.enabled ? <div className="button-row"><Button variant="danger" disabled={task.busy} onClick={() => { void task.run(async () => { const ack = await command<AuthoringAck>(apiPath(campaignId, `/entries/${encodeURIComponent(entryId)}/publication/unpublish`), { expectedArticleRevisionId: source.id, expectedPublicationVersion: version, expectedPolicyVersion: policy.version }); if (alive.current) { setVersion(ack.version); setPreview(null); setNotice(t("Artikel zurückgenommen. Öffentliche Suche, Feed und alte Adressen geben ihn nicht mehr aus.")); onChanged(); } }); }}>{t("Artikel zurücknehmen")}</Button>{policy.enabled && deliveryEnabled ? <a href={`/w/${encodeURIComponent(policy.publicKey)}/${encodeURIComponent(policy.worldSlug)}/${encodeURIComponent(published.publicSlug)}`} target="_blank" rel="noreferrer">{t("Öffentlichen Artikel öffnen")}</a> : null}</div> : null}
  </section>;
}

function MintChoices({ campaignId, passageId, selected, onChange }: { campaignId: string; passageId: string; selected: string[]; onChange: (ids: string[]) => void }) {
  const [open, setOpen] = useState(false), [revision, setRevision] = useState(0);
  const mints = useResource<MintReceipt[]>(open ? apiPath(campaignId, `/passages/${encodeURIComponent(passageId)}/provenance`) : null, revision);
  return <details onToggle={event => setOpen(event.currentTarget.open)}><summary>{t("Herkunftsbelege für den öffentlichen Feed wählen")}</summary>{mints.loading ? <Loading /> : null}{mints.error ? <Notice error>{mints.error}<Button onClick={() => setRevision(value => value + 1)}>{t("Erneut laden")}</Button></Notice> : null}{mints.data?.filter(mint => PUBLIC_MINT_KINDS.some(kind => kind === mint.kind)).map(mint => <label className="check-label" key={mint.id}><input type="checkbox" checked={selected.includes(mint.id)} onChange={e => onChange(e.target.checked ? [...selected, mint.id].sort() : selected.filter(id => id !== mint.id))} />{mint.kind} · {new Date(Number(mint.confirmedAt)).toLocaleDateString(locale())}</label>)}{mints.data?.length === 0 ? <p>{t("Für diese Passage liegt kein bestätigter Beleg vor.")}</p> : null}</details>;
}

function PublicationRoutes({ campaignId, policy, revision, onDirty, onChanged }: { campaignId: string; policy: PublicationPolicy; revision: number; onDirty: (dirty: boolean) => void; onChanged: () => void }) {
  const routes = useResource<PublicationRoute[]>(apiPath(campaignId, "/publication/routes"), revision), entries = useResource<EntrySummary[]>(apiPath(campaignId, "/entries"), revision);
  const [kind, setKind] = useState<PublicationRoute["kind"]>("article"), [route, setRoute] = useState(""), [entryId, setEntryId] = useState(""), [sourceUrl, setSourceUrl] = useState(""), [confirmed, setConfirmed] = useState(false), [notice, setNotice] = useState("");
  const sources = useResource<{ legacyRoutes: PublicationRoute[] }>(kind === "legacy" && entryId ? apiPath(campaignId, `/entries/${encodeURIComponent(entryId)}/publication/sources`) : null, revision);
  const task = useTask(), command = useCommand();
  useEffect(() => { onDirty(!!route || !!sourceUrl); return () => onDirty(false); }, [route, sourceUrl, onDirty]);
  return <section className="panel"><h2>{t("Alte Adressen erhalten")}</h2><p>{t("Welt- und Artikeladressen bleiben bei einer Umbenennung als Weiterleitung erhalten. Eine bestätigte Importadresse kann auf diesem Server zugeordnet werden. Weiterleitungen auf dem ursprünglichen fremden Host benötigen dessen Betreiber.")}</p>{task.error || routes.error ? <Notice error>{task.error || routes.error}</Notice> : null}{notice ? <Notice>{notice}</Notice> : null}
    {routes.data?.map(item => <div key={`${item.kind}:${item.route}`} className="button-row"><code>{item.route}</code><span>{item.kind}</span><Button disabled={task.busy} onClick={() => void task.run(async () => { await command(apiPath(campaignId, "/publication/routes/remove"), { expectedPolicyVersion: policy.version, kind: item.kind, route: item.route }); onChanged(); })}>{t("Weiterleitung entfernen")}</Button></div>)}
    <form onSubmit={event => { event.preventDefault(); void task.run(async () => { await command(apiPath(campaignId, "/publication/routes"), { expectedPolicyVersion: policy.version, kind, route, entryId: kind === "world" ? null : entryId, sourceUrl: kind === "legacy" ? sourceUrl : null }); setRoute(""); setSourceUrl(""); setConfirmed(false); setNotice(t("Adresse zugeordnet.")); onChanged(); }); }}><fieldset disabled={task.busy} className="authoring-controls"><label>{t("Adressart")}<select aria-label={t("Adressart")} value={kind} onChange={e => { setKind(e.target.value as PublicationRoute["kind"]); setConfirmed(false); }}><option value="article">{t("Artikelalias")}</option><option value="world">{t("Weltalias")}</option><option value="legacy">{t("Bestätigte Wiki-Importadresse")}</option></select></label><label>{kind === "legacy" ? t("Alter Wiki-Pfad auf diesem Server") : t("Bisheriger Adressname")}<input required maxLength={2048} value={route} onChange={e => { setRoute(e.target.value); setConfirmed(false); }} /></label>
      {kind !== "world" ? <label>{t("Zielartikel")}<select aria-label={t("Zielartikel")} required value={entryId} onChange={e => { setEntryId(e.target.value); setConfirmed(false); }}><option value="">{t("Veröffentlichten Artikel wählen")}</option>{entries.data?.map(entry => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label> : null}
      {kind === "legacy" ? <>{sources.loading ? <Loading /> : null}{sources.error ? <Notice error>{sources.error}</Notice> : null}{sources.data?.legacyRoutes.map(source => <Button key={`${source.route}:${source.sourceUrl}`} onClick={() => { setRoute(source.route); setSourceUrl(source.sourceUrl!); setConfirmed(false); }}>{t("Nachgewiesene Quelle wählen: {adresse}", { adresse: source.sourceUrl ?? "" })}</Button>)}{sources.data?.legacyRoutes.length === 0 ? <p>{t("Für diesen Artikel liegt keine bestätigte Wiki-Importadresse vor.")}</p> : null}<label>{t("Nachgewiesene ursprüngliche Quelladresse")}<input required type="url" value={sourceUrl} onChange={e => { setSourceUrl(e.target.value); setConfirmed(false); }} /></label><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /> {t("Ich bestätige diese Zuordnung zur nachgewiesenen Importquelle.")}</label></> : null}
      <Button type="submit" disabled={kind === "legacy" && !confirmed}>{t("Adresse zuordnen")}</Button></fieldset></form>
  </section>;
}
