// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Kaya Yesilyurt - Atlas Chronicles. Siehe LICENSE.
export { RuleValidationError, RULE_LIMITS, stableJson } from "./validation.ts";
export { haelt, haelt_etikett, erfahrungsgrad, parseProjectedKnowledge, type Experience, type HeldPassage, type ProjectedKnowledge } from "./knowledge.ts";
export { ENGINE_VERSION, RNG_ALGORITHM, parseDice, parseFormula, parseFormulaAst, parseFormulaDetailed, tokenizeFormula, inferFormulaType, evaluateFormula, parseEvaluationContext, type Scalar, type FormulaType, type Formula, type FormulaFieldTypes, type FormulaToken, type FormulaTokenKind, type FormulaErrorCode, type FormulaParseDetail, type EvaluationContext, type DiceTrace, type TraceStep, type FormulaResult } from "./formula.ts";
export { RULE_PACKAGE_SCHEMA_VERSION, parseRulePackage, validateFieldValue, validateEntityFields, defaultActorFields, evaluateAction, replayAction, RulePackageRegistry, type FieldSchema, type RuleAction, type RuleMigration, type MigrationStep, type RuleLayoutSection, type RuleLayout, type RulePackage, type PackagePin, type ActionResult } from "./package.ts";
export { RULE_PRESENTATION_SCHEMA_VERSION, parseRuleCollections, parseRulePresentation, decodeRuleCollectionValue, encodeRuleCollectionValue, validateRuleCollections, visiblePresentationNodeIds, type RuleCollection, type RulePresentationRender, type RulePresentationNode, type RulePresentationGroup, type RulePresentationField, type RulePresentationComputed, type RulePresentationVital, type RulePresentationCollection, type RulePresentationAbilities, type RulePresentationConditions, type RulePresentationActions, type RulePresentationV3, type RulePresentationContext } from "./presentation-v3.ts";
export { previewPackageMigration, type MigrationEntity, type MigrationPreview } from "./migration.ts";
export { DEMO_RULE_PACKAGE } from "./demo.ts";
export { RULE_PACKAGE_SCHEMA_VERSION_V2, OUTCOME_VERSION, parseRulePackageV2, parseSupportedRulePackage, validatePackageFields, defaultSupportedActorFields, evaluateComputedFields, evaluateVitals, depletedDefeatVitals, evaluateSupportedAction, replaySupportedAction, supportedPackageContentHash, SupportedRulePackageRegistry, abilityOverview, type RuleModifier, type ModifierTarget, type RuleAbility, type AbilityKind, type RuleCondition, type RuleAbilityRules, type AppliedModifier, type AbilityOverview, type RulePackageV2, type RuleActionV2, type RuleSelfTestV2, type RuleVital, type VitalReading, type AnyRulePackage, type AnyActionResult, type ActionResultV2, type RuleOutcome, type RuleAttribution, type RuleAssertion, type ComputedField, type OutcomeComparison, type OutcomeLabel, type OutcomeBand, type ClassifiedOutcome, type OutcomeExpressionTrace } from "./package-v2.ts";
export { previewSupportedPackageMigration } from "./supported-migration.ts";
export { CHRONICLE_LOOT_DECK, CHRONICLE_LOOT_SPREAD, CHRONICLE_LOOT_IMAGE_DIR, type ChronicleLootCard, type ChronicleLootRarity, type ChronicleLootEmblem } from "./templates/chronicle-heroes-loot.ts";
export { createChronicleHeroesPackage, CHRONICLE_HEROES_PACKAGE, CHRONICLE_VERSION, CHRONICLE_DEFAULT_SKILLS, CHRONICLE_EXAMPLE_CHARACTERS, CHRONICLE_FIELDS, CHRONICLE_FIELD_LABELS, CHRONICLE_ATTRIBUTION, CHRONICLE_RULE_GUIDANCE, CHRONICLE_START_POINTS, CHRONICLE_MAX_ARMOUR, CHRONICLE_SKILL_LIBRARY, CHRONICLE_MAX_SKILLS, CHRONICLE_ARMOUR_FIELD, CHRONICLE_FUNKEN_FIELD, parseChronicleSkills, chronicleSkillField, chronicleBonusField, CHRONICLE_XP_FIELD, CHRONICLE_XP_SKILLS_FIELD, CHRONICLE_ABILITY_FIELD, CHRONICLE_CONDITION_FIELD, CHRONICLE_START_ABILITY_BUDGET, CHRONICLE_POINTS_PER_XP, CHRONICLE_MIGRATION_1_TO_2, CHRONICLE_ARCHETYPES, type ChronicleField, type ChronicleSkill, type ChroniclePackageOptions, type ChronicleExampleCharacter, type ChronicleArchetype } from "./templates/chronicle-heroes.ts";
export { CHRONICLE_ABILITY_LIBRARY, CHRONICLE_CONDITIONS, CHRONICLE_ABILITY_PRICES, CHRONICLE_ABILITY_MINIMUMS, type ChronicleAbilityEntry, type ChronicleConditionEntry, type ChronicleEffect, type ChronicleEffectTarget, type ChronicleAbilityField } from "./templates/chronicle-heroes-faehigkeiten.ts";
export { CHRONICLES_LITE_PACKAGE, CHRONICLES_LITE_SKILLS, CHRONICLES_LITE_GROUP_LABELS, chroniclesLiteSkillField, type ChroniclesLiteGroup, type ChroniclesLiteSkill } from "./templates/chronicles-lite.ts";
export { D20_REFERENCE_PACKAGE, THREE_D20_REFERENCE_PACKAGE } from "./templates/universal-reference.ts";
export { FIFTH_EDITION_REFERENCE_PACKAGE } from "./templates/fifth-edition-reference.ts";
export { FIFTH_EDITION_SRD_PACKAGE } from "./templates/fifth-edition-srd.ts";
export { UNIVERSAL_REFERENCE_PACKAGES } from "./templates/universal-reference-catalog.ts";
// `How to be a Hero` steht bewusst nicht hier, sondern in `./examples.ts` — siehe dort.
export { RULE_RUNTIME_CONTRACT, buildRuleRuntime, previewRuleRuntime, type RuleRuntimeIdentity, type RuleRuntimeAction, type RuleRuntimeAbilityUse, type RuleRuntimePassiveEffect, type RuleRuntimeActionState, type RuleRuntimeSection, type RuleRuntime, type RuleRuntimePreview } from "./runtime.ts";
