// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Kaya Yesilyurt - Atlas Chronicles. Siehe LICENSE.
export { RuleValidationError, RULE_LIMITS, stableJson } from "./validation.ts";
export { haelt, haelt_etikett, erfahrungsgrad, parseProjectedKnowledge, type Experience, type HeldPassage, type ProjectedKnowledge } from "./knowledge.ts";
export { ENGINE_VERSION, RNG_ALGORITHM, parseDice, parseFormula, parseFormulaAst, parseFormulaDetailed, tokenizeFormula, inferFormulaType, evaluateFormula, parseEvaluationContext, type Scalar, type FormulaType, type Formula, type FormulaFieldTypes, type FormulaToken, type FormulaTokenKind, type FormulaErrorCode, type FormulaParseDetail, type EvaluationContext, type DiceTrace, type TraceStep, type FormulaResult } from "./formula.ts";
export { RULE_PACKAGE_SCHEMA_VERSION, parseRulePackage, validateFieldValue, validateEntityFields, defaultActorFields, evaluateAction, replayAction, RulePackageRegistry, type FieldSchema, type RuleAction, type RuleMigration, type MigrationStep, type RulePackage, type PackagePin, type ActionResult } from "./package.ts";
export { previewPackageMigration, type MigrationEntity, type MigrationPreview } from "./migration.ts";
export { DEMO_RULE_PACKAGE } from "./demo.ts";
export { RULE_PACKAGE_SCHEMA_VERSION_V2, OUTCOME_VERSION, parseRulePackageV2, parseSupportedRulePackage, validatePackageFields, defaultSupportedActorFields, evaluateComputedFields, evaluateVitals, depletedDefeatVitals, evaluateSupportedAction, replaySupportedAction, supportedPackageContentHash, SupportedRulePackageRegistry, type RulePackageV2, type RuleActionV2, type RuleSelfTestV2, type RuleVital, type VitalReading, type AnyRulePackage, type AnyActionResult, type ActionResultV2, type RuleOutcome, type RuleAttribution, type RuleAssertion, type ComputedField, type OutcomeComparison, type OutcomeLabel, type OutcomeBand, type ClassifiedOutcome, type OutcomeExpressionTrace } from "./package-v2.ts";
export { previewSupportedPackageMigration } from "./supported-migration.ts";
export { createChronicleHeroesPackage, CHRONICLE_HEROES_PACKAGE, CHRONICLE_VERSION, CHRONICLE_DEFAULT_SKILLS, CHRONICLE_EXAMPLE_CHARACTERS, CHRONICLE_FIELDS, CHRONICLE_FIELD_LABELS, CHRONICLE_ATTRIBUTION, CHRONICLE_RULE_GUIDANCE, CHRONICLE_START_POINTS, CHRONICLE_MAX_ARMOUR, CHRONICLE_ARMOUR_FIELD, CHRONICLE_FUNKEN_FIELD, parseChronicleSkills, chronicleSkillField, chronicleBonusField, type ChronicleField, type ChronicleSkill, type ChroniclePackageOptions, type ChronicleExampleCharacter } from "./templates/chronicle-heroes.ts";
// `How to be a Hero` steht bewusst nicht hier, sondern in `./examples.ts` — siehe dort.
